### ISSUE TITLE
problem compiling bundles on Mac

### ISSUE THREAD

**Issue by mpagowski** [JCSDA/singularity#8]
First
singularity pull shub://JCSDA/singularity
I remove build directory and start from scratch. Then ecbuild /jedi/code/ufo-bundle (will fail similarly with any bundle with fresh git pull)
After make -j4

[ 95%] Linking CXX executable test_ufo_geovals_marine
CMakeFiles/test_ufo_geovals_marine.dir/mains/TestGeoVaLs.cc.o: In function `test::GeoVaLs<ufo::UfoTrait>::register_tests() const':
/jedi/code/ufo-bundle/oops/src/test/interface/GeoVaLs.h:155: undefined reference to `boost::unit_test::test_suite::test_suite(boost::unit_test::basic_cstring<char const>, boost::unit_test::basic_cstring<char const>, unsigned long)'
CMakeFiles/test_ufo_geovals_marine.dir/mains/TestGeoVaLs.cc.o: In function `boost::unit_test::make_test_case(boost::function<void ()> const&, boost::unit_test::basic_cstring<char const>, boost::unit_test::basic_cstring<char const>, unsigned long)':
/usr/local/include/boost/test/tree/test_unit.hpp:249: undefined reference to `boost::unit_test::ut_detail::normalize_test_case_name[abi:cxx11](boost::unit_test::basic_cstring<char const>)'

....

That happens only on my laptop (and works fine on the desktop).

**Comment by mer-a-o** [comment]
Hi @mpagowski. Are you using the develop branch of oops, ioda, and ufo? With the changes we made to remove Boost unit testing you need to use the latest version of these repositories. [This](https://github.com/orgs/JCSDA/teams/jedi/discussions/22)
discussion has more information on the details.

**Comment by mpagowski** [comment]
I must have forgotten a pull in some directory, it took a few hours to
compile all on my laptop but it did, thanks
